name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  # See:
  #  - https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  #  - https://packaging.python.org/en/latest/tutorials/packaging-projects/
  #  - https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # See https://github.com/actions/checkout/issues/261.
          ref: ${{ github.event.pull_request.head.sha }}
          # Grab entire history for VCS-based version.
          fetch-depth: 0

      # See https://github.com/prefix-dev/setup-pixi.
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.12
        with:
          pixi-version: v0.54.2
          environments: dev
          # We deliberately disable the cache and don't generate a lockfile
          # because we always want to use latest versions in CI.
          cache: false

      - name: Create packages
        run: pixi run -e dev --frozen --locked just build

      #    - name: Publish distribution 📦 to Test PyPI
      #      uses: pypa/gh-action-pypi-publish@release/v1
      #      with:
      #        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #        repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
